name: Build Keystone WASM Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag points to master
        run: |
          set -euo pipefail
          git fetch origin master:refs/remotes/origin/master
          if ! git merge-base --is-ancestor "${GITHUB_SHA}" "origin/master"; then
            echo "Tag ${GITHUB_REF_NAME} does not point to a commit on master" >&2
            exit 1
          fi

      - name: Build keystone.wasm via Docker
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          set -euo pipefail
          docker build --target artifacts --output type=local,dest=build-output .
          ls -R build-output/dist

      - name: Prepare release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          if gh release view "${TAG_NAME}" >/dev/null 2>&1; then
            echo "Release ${TAG_NAME} already exists."
          else
            gh release create "${TAG_NAME}" \
              --target "${GITHUB_SHA}" \
              --title "${TAG_NAME}" \
              --notes ""
          fi

      - name: Upload keystone.wasm asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          asset_path="build-output/dist/wasm/keystone.wasm"
          if [ ! -f "$asset_path" ]; then
            echo "Expected asset not found at ${asset_path}" >&2
            exit 1
          fi
          gh release upload "${TAG_NAME}" "${asset_path}" \
            --clobber \
            --content-type application/wasm
